### ISSUE TITLE
Homebrew formula warnings

### ISSUE THREAD

**Issue by dsiebel** [hendrikmaus/helm-templexer#44] opened 2021-06-02 13:16 UTC
When install helm-templexer via Homebrew I get the following warnings:

```
Warning: Calling `cellar` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the hendrikmaus/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/hendrikmaus/homebrew-tap/Formula/helm-templexer.rb:16

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the hendrikmaus/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/hendrikmaus/homebrew-tap/Formula/helm-templexer.rb:17

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the hendrikmaus/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/hendrikmaus/homebrew-tap/Formula/helm-templexer.rb:18
```

These warnings are also displayed on any subsequent call to `homebrew install|update` after installation of helm-templexer.

**Comment by hendrikmaus** [comment] 2021-06-02 13:35
Duplicate of: https://github.com/hendrikmaus/homebrew-tap/issues/2
However I think it makes sense to also track this issue here where people would expect it.

**Comment by hendrikmaus** [comment] 2021-06-08 07:14
Resolved.

**Closed by hendrikmaus** 2021-06-08 07:14 UTC
